### ISSUE TITLE
Error in the resource settings when a separator is the first item

### ISSUE THREAD

**Issue by jarosm** [TriggerAu/AlternateResourcePanel#88]
If you configure resource settings and move a separator to the top of the list of resources ("Move Up" or "Move to Top" button), then an error is generated.

`[EXC 21:53:39.277] InvalidOperationException: Operation is not valid due to the current state of the object
	System.Linq.Enumerable.Last[ResourcePosition] (IEnumerable`1 source)
	KSPAlternateResourcePanel.ARPWindowResourceConfig.DrawWindow (Int32 id)
	KSPPluginFramework.MonoBehaviourWindow.DrawWindowInternal (Int32 id)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
[ERR 21:53:39.279] GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced)`

**Comment by Arkil81** [comment]
I've encountered this issue as well. I created a new separator in the resource settings panel, then pressed "Move to Top". After closed the settings to check how it looks, I opened up the settings panel again. I found it to be empty, save for one separator item. I couldn't edit the settings anymore.

To fix this issue, I looked up the settings.cfg file in "---/Gamedata/TriggerTech/KSPAlternateResourcePanel/PluginData" and edited out the first "Item" block from the "ResourcesStorage" block (it has IsSeparator = True)

You have to do the edit out of flight mode, since the mod saves its current settings whenever you leave flight mode, overwriting any changes you do in-flight alt-tabbed. Quicksaving, editing and loading quicksave doesn't work either.
